### ISSUE TITLE
Custom keymaps configuration option

### ISSUE THREAD

**Issue by eslam-allam** [isakbm/gitgraph.nvim#11]
I usually like to map "q" to close the current buffer for various files such as http, diffview, etc... diffview has a configuration option for keymaps which uses vim.keymap.set under the hood. For others that don't provide this kind of option, I resort to using a filetype autocmd to set said keymap. Unfortunately that doesn't seem possible because of how the file type is being set in this plugin 

```lua
vim.cmd('noautocmd silent! set filetype=gitgraph')
```

Would it be possible to add a keymaps config option like diffview does or at least not use 'noautocmd' if it's not necessary?

**Comment by isakbm** [comment]
Can you show me more specifically what you mean?

**Comment by eslam-allam** [comment]
Here's my current lazy.nvim configuration for sindrets/diffview.nvim:

```lua
return {
  "sindrets/diffview.nvim",
  keys = {
    { "<leader>gd", "<cmd>DiffviewOpen<CR>", desc = "Diff View", mode = "n" },
    { "<leader>gf", "<cmd>DiffviewFileHistory %<CR>", desc = "File History (This)", mode = "n" },
    { "<leader>gF", "<cmd>DiffviewFileHistory<CR>", desc = "File History (All)", mode = "n" },
  },
  opts = {
    keymaps = {
      view = {
        q = "<cmd>DiffviewClose<CR>",
      },
    },
  },
}
```

in the opts table you will see one of the keys is called "keymaps". This key allows me to set keymaps to be applied in the diffview windows. In this specific example, I'm setting "q" to "DiffviewClose" to close the diffview tab. I would like a similar option in gitgraph.

Alternatively, if a plugin doesn't provide this kind of option I usually do something like this:

```lua
local cmd = vim.api.nvim_create_autocmd

-- close some filetypes with <q>
cmd("FileType", {
  group = ugroup("close_with_q"),
  pattern = {
    "gitgraph",
  },
  callback = function(event)
    ---@type string|function
     vim.bo[event.buf].buflisted = false
     vim.keymap.set("n", "q", "<cmd>close<cr>", { buffer = event.buf, silent = true })
  end,
})
```

This doesn't work with gitgraph because the gitgraph draw command doesn't trigger autocmds because of the use of "noautocmd" here (gitgraph.lua:1821):

```lua
vim.cmd('noautocmd silent! set filetype=gitgraph')
```

I hope this clears it up for you.

**Comment by isakbm** [comment]
Thanks, that was very clear, I'm not the author of this `vim.cmd('noautocmd silent! set filetype=gitgraph')` that would be @letieu  I believe, ... I wonder why he added the `noautocmd` 🤔  would be nice to get an explanation, perhaps you already know @eslam-allam ? I would like the answer to this for curiosity and learnings sake.

I'll consider just adding a `close` command that you could bind in whatever way you like @eslam-allam , in the meantime I'll wait a bit for a reply on the purpose or need for or reasons for wanting to have `noautocmd` 🤔

**Comment by letieu** [comment]
we can delete `noautocmd`, I just copy it from mini.starter plugin, but I think in out case, we don't need it. 

if use `noautocmd` , we can't listen the file type with autocmd.

I was created a new PR, please take a look.
https://github.com/isakbm/gitgraph.nvim/pull/16
