### ISSUE TITLE
Show/highlight graph of specific branch only

### ISSUE THREAD

**Issue by gennaro-tedesco** [isakbm/gitgraph.nvim#12]
Already using this plugin so much, it is incredible how much it simplifies finding commits and browsing through the history!

A suggestion that is perhaps out of scope or of high complexity, hence feel free to ignore it and close if you think so. Would it be possible/in scope to show the graph of a specific branch only? Generally speaking during development people are concerned with following the history of a feature/bug-fix or such, namely of one specific piece of work at a time, and they look for original branching point, commits, merge commit - essentially all you show now, only for that specific branch (to avoid graphical cluttering).

I thought one could make `require("gitgraph").draw({branch = <branch>})` accept an optional argument, if given only the single branch history is shown, if not the entire git graph? Or another idea could be to gray out the other branches (remove the highlights) and, though showing them nevertheless, only highlight the chosen one.

**Comment by isakbm** [comment]
What you are describing sounds like the default behavior if you call `draw` without the `all`, then it will draw the graph relevant for the commit you are currently checked out on?

But please correct me if I'm wrong, perhaps you mean something subtly different from this default behavior?

**Comment by gennaro-tedesco** [comment]
You are right, I had not paid attention to the argument `all=true` at all, and by removing it I see exactly the behaviour that I describe above. Perfect so, and sorry for the noise!
