### ISSUE TITLE
Feature Request: Open GitGraph buffer in `nowrap` mode

### ISSUE THREAD

**Issue by kdheepak** [isakbm/gitgraph.nvim#17]
I have been experimenting with using `git lg` as an alias for `nvim -c ":GitGraph"` where `:GitGraph` is a command I wrote that runs the lua code to launch the graph generated by this plugin.

Sometimes I'm just interested in the graph presentation, so I might `git lg`, get a sense for what is going on and `:q` to exit. And the width of the terminal I have is not what I would have if I wanted to see the graph in its entirety. In this case, because of wrapping, it becomes difficult to view:

<img width="514" alt="image" src="https://github.com/user-attachments/assets/69381572-1056-4f43-b32d-fadbd1316503">

Here's the output of [`serie`](https://github.com/lusingander/serie/) in that same width:

<img width="522" alt="image" src="https://github.com/user-attachments/assets/20c43f88-9d20-42d7-87f8-7f6069bbc10c">

---

It would be nice if the git graph were always launched in `nowrap` mode.

**Comment by isakbm** [comment]
Agreed. BTW I am considering splitting it up into two windows and two buffers L | R . Both windows L and R would be scroll locked, and I would add `nowrap` to both buffers. The window on the left (L) would have the graph, and the window on the right (R) would have the commit data.

**Comment by kdheepak** [comment]
That's a neat idea! Often times I'm only interested in the commit hash and the first few words of the commit message. So maybe that can be in the first buffer and the remaining can be in the other?

`serie` supports a horizontal split to show additional information when hitting `Enter`, which is something you may want to consider:

<img width="757" alt="image" src="https://github.com/user-attachments/assets/6e348472-b6eb-42be-8b3e-4261c6429775">

**Comment by isakbm** [comment]
I'm unable to reproduce the wrapping issue that you are having 🤷 

Could you give me a list of steps I need to take to reproduce it?

Is it some setting in your nvim or your terminal?

**Comment by isakbm** [comment]
Here's a screenshot of me trying to force line wrap to happen, but to no avail.

![image](https://github.com/user-attachments/assets/597b7f64-669c-4562-ba79-20412e6a86ab)

**Comment by isakbm** [comment]
Nevermind, turns out I just always turn off linewrap, and have it globally turned off in my config 😅 

When I turned off my global `vim.opt.wrap = false` I was able to reproduce I think, here's a screenshot

![image](https://github.com/user-attachments/assets/26580236-4054-4f1e-bc91-924c05d6dfe4)

**Comment by isakbm** [comment]
Should now be fixed, please give it a try @kdheepak

**Comment by kdheepak** [comment]
It works perfectly now for me! Thank you!
