### ISSUE TITLE
Comparison with vim-flog

### ISSUE THREAD

**Issue by TamaMcGlinn** [isakbm/gitgraph.nvim#19]
Hi! I like the screenshots; it looks very similar to what I'm currently using, [vim-flog](https://github.com/rbong/vim-flog/). I'm just opening this here to make sure you are aware of that plugin, maybe you can borrow concepts / steal some code. We're all in this open-source world together, let's make sure we help each other out where possible.

The author of vim-flog opened [this opposite issue](https://github.com/rbong/vim-flog/issues/134) to compare; that's how I encountered yours.

**Comment by isakbm** [comment]
Fully aware. Closing this issue as it clutters real issues ;)
