### ISSUE TITLE
Set a filetype on buffer

### ISSUE THREAD

**Issue by robertgzr** [isakbm/gitgraph.nvim#2]
to allow running code by setting up a filetype autocmd, for e.g. binding custom keymaps

**Comment by isakbm** [comment]
Sounds like a great idea!

Could you be a bit more specific or provide an example?

**Comment by isakbm** [comment]
I think I understand now, and I think this should do the trick?

```lua
vim.api.nvim_buf_set_option(M.buf, 'filetype', 'gitgraph.nvim')
```

🤞

**Comment by robertgzr** [comment]
@isakbm that is the deprecated API, `vim.api.nvim_set_option_value('filetype', 'gitgraph', { buf = buf })` would be the new one

see https://neovim.io/doc/user/deprecated.html#nvim_buf_set_option()

**Comment by robertgzr** [comment]
also i think other plugins omit the `.nvim` suffix from everything (filetypes, bufnames, package names)

**Comment by isakbm** [comment]
I will use the updated api and remove .nvim 🙌

I'm not at the computer right now though. Will get it by EOD.

**Comment by robertgzr** [comment]
sent a PR :)

**Comment by isakbm** [comment]
Beautiful 😍
