### ISSUE TITLE
Error when running first time 

### ISSUE THREAD

**Issue by Xouzoura** [isakbm/gitgraph.nvim#6]
Hi, when running the default key to get the signs I get this error:

Ubuntu, nvim version 0.10 with lazy installation as specified in the installation part. 

E5108: Error executing lua: ...ra/.local/share/nvim/lazy/gitgraph.nvim/lua/gitgraph.lua:1228:
 attempt to index local 'below' (a nil value)
stack traceback:
        ...ra/.local/share/nvim/lazy/gitgraph.nvim/lua/gitgraph.lua:1228: in function 'gitgra
ph'
        ...ra/.local/share/nvim/lazy/gitgraph.nvim/lua/gitgraph.lua:2030: in function 'draw'
        /home/xouzoura/.config/nvim/lua/plugins/gitgraph.lua:17: in function </home/xouzoura/
.config/nvim/lua/plugins/gitgraph.lua:16>

**Comment by isakbm** [comment]
Most likely found the cause.

Will aim for a patch within 24 hours. 🤞

**Comment by Xouzoura** [comment]
No worries, thanks a lot, plugin looks awesome

**Comment by isakbm** [comment]
This should now be fixed.
