### ISSUE TITLE
It doesn't start 😢 

### ISSUE THREAD

**Issue by daUnknownCoder** [isakbm/gitgraph.nvim#8]
Hey there, I've been watching those git-graph posts for a while now and happy for you to publish this thing to the neovim community ❤️...

But this is not working (sadly):

https://github.com/user-attachments/assets/fb1e91f3-304f-42a9-9dd2-3b056178f624

I also waited for around a minute, which didn't help

**Comment by isakbm** [comment]
Dont worry.There are known and expected bugs / performance limitations that I will be addressing asap :) 

Thanks for bringing this up to my attention!

**Comment by isakbm** [comment]
Most likely found the cause.

Will aim for a patch within 24 hours. 🤞

**Comment by isakbm** [comment]
This should now be fixed, please verify if you can :)
